### ISSUE TITLE
JSNAPy tries to login without password

### ISSUE THREAD

**Issue by ydnath** [Juniper/jsnapy#224] opened 2017-01-30 16:05 UTC
When I am trying to run JSNAPy from CLI without providing a password (with a hope that it will ask for one) the tool would actually try to create a Device and connect, which obviously fails and only after this ask for the password.

The second connect might also fail because connect function would recursively call itself dropping some parameters, but this seems to be fixed recently in git (parameters added in the recursive call).

My question is how to avoid the first login attempt with no password?

@ksator says

Using the command line tool, the only way I found so far is using this command:
"jsnapy --snapcheck -f configfile.yml -v -t <IP> -l username -p password -P 830"
It is not required <IP> is defined in the devices.yml (jsnapy inventory file).
But this is not an option when you have several devices

**Comment by nskalis** [comment] 2017-02-01 10:13
+1 

it seems that the 1st connection is in port 22, but it tries without the password so it fails, while the 2nd attempt for connecting is made using the default port 830 which should not be the case

the issue is with the version on PyPI, the version on GitHub is not suffering from this bug.

please update PyPI :)

**Comment by a-v-popov** [comment] 2017-02-01 12:40
No, git version still make a first connection attempt without password.

**Comment by eeishaan** [comment] 2017-03-04 10:40
@ydnath I think this has to do with how PyEZ works. @vnitinv we need your help here.
I suspect that the first attempt is necessary. Consider scenarios where the user doesn't want to use the password and wants to use the ssh key instead.

**Comment by vnitinv** [comment] 2017-06-19 06:58
This is as per design. If the password is not configured, we try to login via ssh configuration. If that fails, we prompt to provide username/password.

Closing this issue. Please re-open if you feel some issue with the design

**Closed by vnitinv** 2017-06-19 06:58 UTC
