### ISSUE TITLE
Calling jsnapy without username and password causes exception instead of prompt

### ISSUE THREAD

**Issue by ddivins** [Juniper/jsnapy#400] opened 2022-06-09 03:55 UTC
### Description of Issue/Question

When running snap and not providing username or password in config.yml or command line, snap will prompt for username and then error out with exceptions and tracebacks and never as for a password, ending with:

Exception: ConnectAuthError(172.25.92.59)

### Setup
config_check.yml:
```
hosts:
      - device: 172.25.92.59

    tests:
       - test_chassis.yml
```

Command:
jsnapy --snap pre -f config_check.yml -v

Note, no username/password is provided

### Steps to Reproduce Issue

Run the above and the below is the output:
```
ddivins@ddivins-mbp jsnap % jsnapy --snap pre -f config_check.yml -v
jsnapy.cfg file location used : /Users/ddivins/Library/CloudStorage/OneDrive-JuniperNetworks,Inc/Documents/PycharmProjects/jsnap/venv/etc/jsnapy
Configuration file location used : /etc/jsnapy
Connecting to device 172.25.92.59 ................

Enter User name: lab

ERROR occurred ConnectAuthError(172.25.92.59)
Exception in thread Thread-1 (connect):
Traceback (most recent call last):
  File "/Users/ddivins/Library/CloudStorage/OneDrive-JuniperNetworks,Inc/Documents/PycharmProjects/jsnap/venv/lib/python3.10/site-packages/jnpr/junos/device.py", line 1347, in open
    self._conn = netconf_ssh.connect(
  File "/Users/ddivins/Library/CloudStorage/OneDrive-JuniperNetworks,Inc/Documents/PycharmProjects/jsnap/venv/lib/python3.10/site-packages/ncclient/manager.py", line 168, in connect
    return connect_ssh(*args, **kwds)
  File "/Users/ddivins/Library/CloudStorage/OneDrive-JuniperNetworks,Inc/Documents/PycharmProjects/jsnap/venv/lib/python3.10/site-packages/ncclient/manager.py", line 135, in connect_ssh
    session.connect(*args, **kwds)
  File "/Users/ddivins/Library/CloudStorage/OneDrive-JuniperNetworks,Inc/Documents/PycharmProjects/jsnap/venv/lib/python3.10/site-packages/ncclient/transport/ssh.py", line 362, in connect
    self._auth(username, password, key_filenames, allow_agent, look_for_keys)
  File "/Users/ddivins/Library/CloudStorage/OneDrive-JuniperNetworks,Inc/Documents/PycharmProjects/jsnap/venv/lib/python3.10/site-packages/ncclient/transport/ssh.py", line 466, in _auth
    raise AuthenticationError("No authentication methods available")
ncclient.transport.errors.AuthenticationError: No authentication methods available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ddivins/Library/CloudStorage/OneDrive-JuniperNetworks,Inc/Documents/PycharmProjects/jsnap/venv/lib/python3.10/site-packages/jnpr/jsnapy/jsnapy.py", line 667, in connect
    dev.open()
  File "/Users/ddivins/Library/CloudStorage/OneDrive-JuniperNetworks,Inc/Documents/PycharmProjects/jsnap/venv/lib/python3.10/site-packages/jnpr/junos/device.py", line 1366, in open
    raise EzErrors.ConnectAuthError(self)
jnpr.junos.exception.ConnectAuthError: ConnectAuthError(172.25.92.59)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ddivins/Library/CloudStorage/OneDrive-JuniperNetworks,Inc/Documents/PycharmProjects/jsnap/venv/lib/python3.10/site-packages/jnpr/jsnapy/jsnapy.py", line 689, in connect
    raise Exception(ex)
Exception: ConnectAuthError(172.25.92.59)
```

### Versions Report
```
ddivins@ddivins-mbp jsnap % jsnapy --version                                                         
JSNAPy version: 1.3.7
ddivins@ddivins-mbp jsnap % python --version
Python 3.10.4
```

**Comment by ddivins** [comment] 2022-06-09 03:59
Problem is in snappy.py line 669:
```
if password is None and action is None:
```

This if statement is not met, if we remove "and action is None" this solves my issue, snippet:
```
 except ConnectAuthError as ex:
                #if password is None and action is None:
                if password is None:
                    password = getpass.getpass(
                        "\nEnter Password for username <%s> : " % username
                    )
                    return self.connect(
                        hostname,
                        username,
                        password,
                        output_file,
                        config_data,
                        action,
                        post_snap,
                        **kwargs
                    )
```

Problem is I have no idea what that "and action is None" is there for or doing so I do not know the safety of removing it.

**Comment by chidanandpujar** [comment] 2024-05-30 12:12
issue is fixed https://github.com/Juniper/jsnapy/pull/402

jsnapy --snap pre -f common_config.yml -v
jsnapy.cfg file location used : /root/jsnapy_test1/venv/etc/jsnapy
Configuration file location used : /root/jsnapy_test1/venv/etc/jsnapy
Connecting to device x.x.x.x ................

Enter User name: xyz

Enter Password for username <xyz> : 
Connecting to device x.x.x.x................
Tests Included: test_chassis_hardware 
Taking snapshot of COMMAND: show chassis hardware 

/jsnapy_test1/jsnapy# jsnapy --version
JSNAPy version: 1.3.8.dev0

**Comment by chidanandpujar** [comment] 2024-06-11 09:37
issue is fixed https://github.com/Juniper/jsnapy/pull/402 , hence closing this issue for now,
Please feel free to re-open, if the issue is reproducible in the latest jsnapy master branch.

Thanks
Chidanand

**Closed by chidanandpujar** 2024-06-11 09:37 UTC
Labels: bug
